# Generated by Django 5.2.1 on 2025-05-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_name',
            new_name='post_id',
        ),
    ]
